# -*- coding: utf-8 -*-
"""Augment an existing SolidWorks-linked workbook with simulation sheets.

This script does not create a new geometry sheet. Instead, it adds missing
simulation/configuration sheets to the exact workbook generated by SolidWorks.
"""

import argparse
import glob
import os
from pathlib import Path

import openpyxl
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
MASTERS_DIR = os.path.join(PROJECT_ROOT, "masters")

# Sheets owned by this script — never treated as a geometry source
SIMULATION_SHEETS = {"Meshing_Parameters", "Materials", "Step_Configuration", "Materials_Library", "Instructions"}

HEADER_FONT = Font(bold=True, color="FFFFFF", size=11)
HEADER_FILL = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
CENTER = Alignment(horizontal="center", vertical="center")

MATERIAL_HEADER_ALIASES = {
    "Density": "Density_kg_m^3",
    "Density_ton_m^3": "Density_kg_m^3",
    "Youngs_modulus": "Youngs_modulus_GPa",
}

MATERIAL_LIBRARY_HEADER_ALIASES = {
    "Density": "Density_kg_m^3",
    "Youngs_modulus": "Youngs_modulus_GPa",
    "Sound_speed": "Sound_speed_m_s",
    "Wavelength": "Wavelength_mm",
}


def _write_header_row(ws, headers, col_widths=None):
    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_idx)
        cell.value = header
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.alignment = CENTER
    if col_widths:
        for col_idx, w in enumerate(col_widths, start=1):
            ws.column_dimensions[get_column_letter(col_idx)].width = w
    ws.freeze_panes = "A2"


def _write_data_row(ws, row_idx, values):
    for col_idx, value in enumerate(values, start=1):
        cell = ws.cell(row=row_idx, column=col_idx)
        cell.value = value
        cell.alignment = CENTER


def _normalize_headers_in_sheet(ws, header_aliases):
    """Rename known legacy headers in row 1; return True when any header changed."""
    changed = False
    for col_idx in range(1, ws.max_column + 1):
        cell = ws.cell(row=1, column=col_idx)
        current = str(cell.value).strip() if cell.value is not None else ""
        replacement = header_aliases.get(current)
        if replacement and replacement != current:
            cell.value = replacement
            changed = True
    return changed


def _ensure_meshing_sheet(wb):
    if "Meshing_Parameters" in wb.sheetnames:
        return False

    ws = wb.create_sheet("Meshing_Parameters")
    headers = [
        "Model_name", "Element_order", "Algorithm", "Characteristic_length_min", "Characteristic_length_max", "Recombine",
        "Num_threads", "Second_order_incomplete", "Msh_version",
    ]
    widths = [40, 14, 10, 28, 28, 12, 12, 24, 12]
    _write_header_row(ws, headers, widths)
    _write_data_row(ws, 2, ["*", 2, 10, 0.5, 2.0, False, 0, True, 4.1])
    return True


def _ensure_materials_sheet(wb):
    if "Materials" in wb.sheetnames:
        return False

    ws = wb.create_sheet("Materials")
    headers = ["Model_name", "Density_kg_m^3", "Youngs_modulus_GPa", "Poissons_ratio"]
    widths = [40, 16, 16, 16]
    _write_header_row(ws, headers, widths)
    _write_data_row(ws, 2, ["*", 2700, 69, 0.33])
    return True


def _ensure_step_sheet(wb):
    if "Step_Configuration" in wb.sheetnames:
        return False

    ws = wb.create_sheet("Step_Configuration")
    headers = [
        "Model_name", "Step_type", "Number_of_frequencies",
        "Lower_frequency_hz", "Upper_frequency_hz", "Output_nsets", "Output_variables",
    ]
    widths = [40, 14, 22, 20, 20, 24, 18]
    _write_header_row(ws, headers, widths)
    _write_data_row(ws, 2, ["*", "frequency", 15, 10000, 100000, "YMAX,YMIN", "U"])
    return True


def _ensure_material_library_sheet(wb):
    if "Materials_Library" in wb.sheetnames:
        return False

    ws = wb.create_sheet("Materials_Library")
    headers = [
        "Material",
        "Density_kg_m^3",
        "Youngs_modulus_GPa",
        "Poissons_ratio",
        "Sound_speed_m_s",
        "Wavelength_mm",
        "Half_wavelength_mm",
        "Quarter_wavelength_mm",
    ]
    widths = [28, 20, 20, 20, 20, 20, 26, 26]
    _write_header_row(ws, headers, widths)

    rows = [
        ["Aluminum 6061-T6", 2700, 69, 0.33],
        ["Aluminum 7075-T6", 2810, 72, 0.33],
        ["Steel 304 Stainless", 8000, 193, 0.29],
        ["Steel 1.2379", 8000, 210, 0.29],
        ["Titanium Ti-6Al-4V", 4506, 103, 0.34],
    ]
    for i, values in enumerate(rows, start=2):
        _write_data_row(ws, i, values)
        ws.cell(row=i, column=5).value = f'=IFERROR(ROUND(SQRT((C{i}*1000000000)/B{i}),2),"" )'
        ws.cell(row=i, column=6).value = f'=IFERROR(ROUND((E{i}*1000)/$B${len(rows)+3},2),"" )'
        ws.cell(row=i, column=7).value = f'=IFERROR(ROUND((F{i}/2),2),"" )'
        ws.cell(row=i, column=8).value = f'=IFERROR(ROUND((F{i}/4),2),"" )'
        
    ws.cell(row=len(rows) + 3, column=1).value = "Frequency (Hz)"
    ws.cell(row=len(rows) + 3, column=1).font = Font(bold=True)
    ws.cell(row=len(rows) + 3, column=2).value = 20000
    return True


def _ensure_instructions_sheet(wb, geometry_sheet_name):
    if "Instructions" in wb.sheetnames:
        return False

    ws = wb.create_sheet("Instructions")
    ws.column_dimensions["A"].width = 42
    ws.column_dimensions["B"].width = 92

    lines = [
        ("MASTER WORKBOOK GUIDE", ""),
        ("Geometry source sheet", geometry_sheet_name),
        ("", ""),
        ("Workflow", "1) In the GUI, create or load a project folder."),
        ("", "2) Place this workbook in 01_Master_Config and augment it if needed."),
        ("", "3) Place STEP files in 02_Geometry_STEP."),
        ("", "4) Optionally assign semantic faces in the 3D preview."),
        ("", "5) Click Run to mesh, solve, and generate 05_Reports/Results_Summary.xlsx."),
    ]

    for r, (a, b) in enumerate(lines, start=1):
        ws.cell(row=r, column=1).value = a
        ws.cell(row=r, column=2).value = b
    return True


def create_master_workbook(file_path, df=None):
    """Create a fresh Master_Config workbook containing a Geometry sheet.

    - Ensures parent directory exists
    - Creates a sheet named 'Geometry' with headers:
      Model_name, Length_mm, Width_mm, Height_mm
    - Writes one sample data row so the sheet isn't empty
    - Saves workbook to `file_path` and returns a status message
    """

    requested_path = Path(file_path)

    # Ensure target directory is the 01_Master_Config folder
    config_dir = requested_path.parent
    if config_dir.name != "01_Master_Config":
        config_dir = config_dir / "01_Master_Config"
    config_dir = config_dir.resolve()
    config_dir.mkdir(parents=True, exist_ok=True)

    path = config_dir / requested_path.name

    # If any .xlsx files already exist in the config dir, do not overwrite
    existing_xlsx = [p for p in config_dir.glob("*.xlsx") if not p.name.startswith("~$")]
    if existing_xlsx:
        raise FileExistsError("One Excel Workbook already in 01_Master_Config. Manually remove it to continue")

    wb = openpyxl.Workbook()

    # Remove default sheet if present to ensure only our named sheets are present
    default_sheet = wb.active
    try:
        wb.remove(default_sheet)
    except Exception:
        pass


    ws = wb.create_sheet("Geometry")

    if df is not None:
        try:
            import pandas as _pd
        except Exception:
            _pd = None

        if _pd is not None and isinstance(df, _pd.DataFrame) and not df.empty:
            export_df = df.copy()
            if "Model_name" in export_df.columns:
                ordered_columns = ["Model_name"] + [c for c in export_df.columns if c != "Model_name"]
                export_df = export_df.loc[:, ordered_columns]
            headers = list(export_df.columns)
            for col_idx, header in enumerate(headers, start=1):
                cell = ws.cell(row=1, column=col_idx)
                cell.value = header
                cell.font = HEADER_FONT
                cell.fill = HEADER_FILL
                cell.alignment = CENTER

            for r_idx, row in enumerate(export_df.itertuples(index=False, name=None), start=2):
                for c_idx, value in enumerate(row, start=1):
                    cell = ws.cell(row=r_idx, column=c_idx)
                    cell.value = value
                    cell.alignment = CENTER
        else:
            # Fallback to sample headers if df invalid
            headers = ["Model_name", "Length_mm", "Width_mm", "Height_mm"]
            for col_idx, header in enumerate(headers, start=1):
                cell = ws.cell(row=1, column=col_idx)
                cell.value = header
                cell.font = HEADER_FONT
                cell.fill = HEADER_FILL
                cell.alignment = CENTER
            sample_row = ["SampleModel", 100.0, 20.0, 10.0]
            for col_idx, val in enumerate(sample_row, start=1):
                cell = ws.cell(row=2, column=col_idx)
                cell.value = val
                cell.alignment = CENTER
    else:
        headers = ["Model_name", "Length_mm", "Width_mm", "Height_mm"]
        for col_idx, header in enumerate(headers, start=1):
            cell = ws.cell(row=1, column=col_idx)
            cell.value = header
            cell.font = HEADER_FONT
            cell.fill = HEADER_FILL
            cell.alignment = CENTER
        sample_row = ["SampleModel", 100.0, 20.0, 10.0]
        for col_idx, val in enumerate(sample_row, start=1):
            cell = ws.cell(row=2, column=col_idx)
            cell.value = val
            cell.alignment = CENTER

    wb.save(path)
    return f"Master workbook created: {path}"


# Backwards compatibility: keep augment_workbook name but delegate to new creator.
def augment_workbook(workbook_path, geometry_sheet_name=None):
    """Compatibility wrapper: create a new master workbook at workbook_path.

    The original augment_workbook accepted a geometry sheet name to augment an
    existing SolidWorks workbook. This project now creates a fresh master
    workbook instead. The wrapper ignores `geometry_sheet_name` and calls the
    new `create_master_workbook` implementation.
    """
    return create_master_workbook(workbook_path)


def _detect_geometry_sheet(wb):
    """Return the single non-simulation sheet name, or None if ambiguous."""
    candidates = [s for s in wb.sheetnames if s not in SIMULATION_SHEETS]
    return candidates[0] if len(candidates) == 1 else None


def _build_parser():
    parser = argparse.ArgumentParser(description="Add simulation sheets to existing SolidWorks workbook")
    parser.add_argument("--master", default="", help="Master basename (no extension). Omit to augment all masters in masters-dir.")
    parser.add_argument("--masters-dir", default="", help="Masters directory (default: masters/)")
    parser.add_argument("--geometry-sheet", default="", help="Geometry sheet name. Auto-detected when workbook has one non-simulation sheet.")
    return parser


def main():
    parser = _build_parser()
    args = parser.parse_args()

    masters_dir = args.masters_dir.strip() or MASTERS_DIR
    master = args.master.strip()
    geometry_sheet = args.geometry_sheet.strip()

    if master:
        workbooks = [os.path.join(masters_dir, f"{master}.xlsx")]
    else:
        workbooks = sorted(glob.glob(os.path.join(masters_dir, "*.xlsx")))

    if not workbooks:
        print(f"[ERROR] No workbooks found in: {masters_dir}")
        return

    for wb_path in workbooks:
        if not os.path.exists(wb_path):
            print(f"[ERROR] Workbook not found: {wb_path}")
            continue

        wb_tmp = openpyxl.load_workbook(wb_path)
        sheet = geometry_sheet

        if not sheet:
            auto = _detect_geometry_sheet(wb_tmp)
            if auto:
                sheet = auto
                if len(workbooks) > 1:
                    print(f"[INFO] {os.path.basename(wb_path)}: auto-detected geometry sheet '{sheet}'")
            else:
                candidates = [s for s in wb_tmp.sheetnames if s not in SIMULATION_SHEETS]
                if not candidates:
                    print(f"[WARN] {os.path.basename(wb_path)}: no geometry sheet found, skipping.")
                    continue
                print(f"\nSheets in {os.path.basename(wb_path)}:")
                for i, s in enumerate(candidates, 1):
                    print(f"  {i}: {s}")
                choice = input("Select geometry sheet number: ").strip()
                try:
                    sheet = candidates[int(choice) - 1]
                except (ValueError, IndexError):
                    print("[ERROR] Invalid selection, skipping.")
                    continue

        augment_workbook(workbook_path=wb_path, geometry_sheet_name=sheet)


if __name__ == "__main__":
    main()
